/**
 * Extensive list of common, safe-for-work adjectives for burner email generation.
 * Combined with nouns and numbers, this provides billions of unique combinations.
 */
export const adjectives: string[] = [
  // Positive traits
  "able", "active", "adorable", "adventurous", "affable", "agile", "alert", "amazing", "ambitious", "amiable",
  "ancient", "angelic", "animated", "artistic", "astute", "athletic", "attentive", "audacious", "authentic", "awesome",
  "balanced", "bashful", "beaming", "beautiful", "beloved", "benevolent", "best", "better", "big", "blazing",
  "blissful", "blithe", "blooming", "bold", "bonny", "boundless", "brainy", "brave", "breezy", "brief",
  "bright", "brilliant", "brisk", "broad", "bubbly", "buoyant", "busy", "calm", "candid", "capable",
  "carefree", "careful", "caring", "casual", "celestial", "central", "certain", "champion", "charming", "cheerful",
  "cherry", "chic", "chief", "chipper", "chivalrous", "choice", "civil", "classic", "clean", "clear",
  "clever", "close", "cloudy", "coastal", "colossal", "colorful", "comely", "comfy", "comic", "common",
  "compact", "complete", "composed", "confident", "constant", "content", "cool", "cooperative", "coral", "cordial",
  "cosmic", "cosy", "courageous", "courteous", "cozy", "crafty", "creative", "crisp", "crystal", "cultured",
  "cunning", "curious", "curly", "current", "cute", "dainty", "dandy", "dapper", "daring", "darling",
  "dashing", "dazzling", "dear", "decent", "decisive", "deep", "delicate", "delightful", "dependable", "determined",
  "devoted", "diamond", "different", "diligent", "diplomatic", "direct", "discreet", "distinct", "divine", "dizzy",
  "docile", "dogged", "doting", "double", "downtown", "dreamy", "driven", "durable", "dusty", "dutiful",
  "dynamic", "eager", "early", "earnest", "earthly", "easy", "eclectic", "edgy", "educated", "effective",
  "efficient", "effortless", "elaborate", "elastic", "elated", "electric", "elegant", "elite", "eloquent", "emerald",
  "eminent", "emotional", "enchanted", "enchanting", "endless", "enduring", "energetic", "engaging", "enigmatic", "enormous",
  "enterprising", "entertaining", "enthusiastic", "entire", "epic", "equal", "essential", "eternal", "ethereal", "ethical",
  "even", "eventual", "evergreen", "everlasting", "exact", "excellent", "exceptional", "excited", "exciting", "exclusive",
  "exotic", "expert", "exquisite", "extra", "extraordinary", "fabulous", "factual", "fair", "faithful", "familiar",
  "famous", "fancy", "fantastic", "far", "fascinating", "fashionable", "fast", "favorable", "fearless", "feisty",
  "festive", "few", "fierce", "fiery", "fine", "first", "fit", "fitting", "flashy", "flawless",
  "fleet", "flexible", "flickering", "flourishing", "flowing", "fluent", "fluffy", "flying", "focal", "focused",
  "fond", "foolproof", "forceful", "foremost", "forest", "forgiving", "formal", "formidable", "forthright", "fortunate",
  "forward", "foxy", "fragrant", "frank", "free", "fresh", "friendly", "frugal", "fruitful", "full",
  "fun", "functional", "fundamental", "funny", "furry", "future", "fuzzy", "gallant", "game", "gaudy",
  "general", "generous", "genial", "genius", "gentle", "genuine", "giant", "gifted", "giving", "glad",
  "glamorous", "gleaming", "gleeful", "glimmering", "glistening", "glittering", "global", "glorious", "glossy", "glowing",
  "golden", "good", "goodly", "gorgeous", "graceful", "gracious", "grand", "grateful", "great", "green",
  "gregarious", "groovy", "grounded", "growing", "guarded", "guided", "guileless", "gutsy", "hallowed", "handsome",
  "handy", "happy", "hardy", "harmless", "harmonious", "healthy", "hearty", "heavenly", "helpful", "heroic",
  "hidden", "high", "hilarious", "hip", "historic", "holistic", "holy", "homely", "honest", "honorable",
  "hopeful", "hospitable", "hot", "huge", "humble", "humorous", "hushed", "hyper", "ideal", "idyllic",
  "illuminated", "illustrious", "imaginative", "immaculate", "immense", "immortal", "impartial", "impeccable", "imperial", "important",
  "impressive", "improved", "incredible", "independent", "indoor", "industrious", "infinite", "influential", "ingenious", "initial",
  "inner", "innocent", "innovative", "inquisitive", "insightful", "inspired", "inspiring", "instant", "integral", "intellectual",
  "intelligent", "intense", "intentional", "interesting", "internal", "intimate", "intrepid", "intuitive", "inventive", "invincible",
  "invisible", "inviting", "iridescent", "irresistible", "jade", "jaunty", "jazzy", "jeweled", "jocular", "jolly",
  "jovial", "joyful", "joyous", "jubilant", "judicious", "juicy", "jumbo", "jumping", "junior", "just",
  "keen", "key", "kind", "kindred", "kingly", "kissable", "knightly", "knowing", "known", "large",
  "lasting", "late", "laughing", "lavish", "lawful", "leading", "lean", "learned", "legal", "legendary",
  "legit", "leisurely", "level", "liberal", "light", "likable", "likely", "limber", "limited", "linear",
  "literate", "little", "live", "lively", "living", "local", "lofty", "logical", "long", "loose",
  "loud", "lovable", "lovely", "loving", "loyal", "lucent", "lucid", "lucky", "luminous", "lunar",
  "lush", "lustrous", "luxurious", "lyrical", "made", "magic", "magical", "magnetic", "magnificent", "majestic",
  "major", "mammoth", "many", "marvelous", "massive", "master", "masterful", "matchless", "material", "mature",
  "maximum", "meaningful", "measured", "meditative", "mellow", "melodic", "memorable", "merciful", "merry", "mesmerizing",
  "metallic", "meteoric", "meticulous", "mighty", "mild", "mindful", "minimal", "mint", "miraculous", "mirthful",
  "mobile", "model", "modern", "modest", "momentous", "monumental", "moral", "motivated", "moving", "much",
  "multi", "municipal", "musical", "mutual", "mysterious", "mystic", "mystical", "mythic", "naive", "narrow",
  "national", "native", "natural", "naval", "near", "neat", "necessary", "neighborly", "neutral", "new",
  "next", "nice", "nifty", "nimble", "noble", "nocturnal", "nominal", "normal", "notable", "noted",
  "novel", "numerous", "nurturing", "objective", "observant", "obvious", "odd", "official", "okay", "old",
  "omniscient", "open", "openhearted", "optimal", "optimistic", "opulent", "orange", "orderly", "organic", "original",
  "ornate", "outdoor", "outer", "outgoing", "outstanding", "overt", "pacific", "painless", "palatial", "pale",
  "panoramic", "parallel", "paramount", "partial", "particular", "passionate", "passive", "past", "pastoral", "patient",
  "patriotic", "peaceful", "peachy", "peak", "peerless", "peppy", "perceptive", "perfect", "periodic", "perky",
  "permanent", "perpetual", "persistent", "personal", "persuasive", "petite", "phenomenal", "philosophical", "physical", "picturesque",
  "pilot", "pioneering", "pious", "pivotal", "placid", "plain", "planetary", "plausible", "playful", "pleasant",
  "pleased", "pleasing", "plentiful", "plucky", "plush", "poetic", "poised", "polished", "polite", "popular",
  "portable", "positive", "possible", "potent", "powerful", "practical", "pragmatic", "praiseworthy", "precious", "precise",
  "preferred", "premier", "premium", "prepared", "present", "presidential", "prestigious", "pretty", "priceless", "primal",
  "primary", "prime", "primo", "princely", "principal", "pristine", "private", "prized", "pro", "proactive",
  "probable", "productive", "professional", "proficient", "profound", "progressive", "prolific", "prominent", "promising", "prompt",
  "proper", "prophetic", "prosperous", "protective", "proud", "proven", "prudent", "public", "pumped", "punctual",
  "pure", "purple", "purposeful", "quaint", "qualified", "quality", "quantum", "queenly", "quick", "quiet",
  "quirky", "radiant", "radical", "rapid", "rare", "rational", "ravishing", "ready", "real", "realistic",
  "reasonable", "recent", "reckless", "recognized", "refined", "reflective", "refreshing", "regal", "regular", "reliable",
  "relieved", "remarkable", "renowned", "reputable", "resilient", "resolute", "resourceful", "respected", "respectful", "responsible",
  "restful", "revered", "rewarding", "rich", "right", "righteous", "ripe", "rising", "ritzy", "riveting",
  "roaring", "robust", "rocking", "romantic", "roomy", "rosy", "round", "royal", "ruby", "rugged",
  "ruling", "rustic", "sacred", "safe", "sage", "saintly", "sanguine", "sapphire", "sassy", "satisfied",
  "saving", "savvy", "scenic", "scholarly", "scientific", "scintillating", "seasoned", "secret", "secure", "sedate",
  "seemly", "select", "selective", "selfless", "sensational", "sensible", "sensitive", "serene", "serious", "settled",
  "several", "sharp", "sheer", "sheltered", "shimmering", "shining", "shiny", "shipshape", "shrewd", "silent",
  "silken", "silky", "silver", "similar", "simple", "sincere", "singular", "sizable", "skilled", "skillful",
  "sleek", "slick", "slight", "slim", "smart", "smashing", "smiling", "smooth", "snappy", "snazzy",
  "snug", "snuggly", "soaring", "sober", "social", "sociable", "soft", "solar", "sole", "solemn",
  "solid", "solitary", "sonic", "soothing", "sophisticated", "sought", "soulful", "sound", "southern", "spacious",
  "sparkling", "special", "spectacular", "speedy", "spellbound", "spherical", "spicy", "spirited", "spiritual", "splendid",
  "spontaneous", "sporting", "sportive", "sporty", "spotless", "sprightly", "spry", "square", "stable", "stainless",
  "standard", "standing", "star", "stark", "starry", "stately", "staunch", "steadfast", "steady", "stellar",
  "sterling", "still", "stimulating", "stirring", "stocky", "stoic", "stoked", "storied", "stout", "straight",
  "strategic", "streamlined", "street", "striking", "strong", "studious", "stunning", "stupendous", "sturdy", "stylish",
  "suave", "sublime", "substantial", "subtle", "successful", "succinct", "sufficient", "sugary", "suitable", "sultry",
  "summary", "summery", "sumptuous", "sunny", "super", "superb", "superior", "supple", "supportive", "supreme",
  "sure", "surreal", "sustainable", "svelte", "sweet", "swift", "sympathetic", "systematic", "tactful", "talented",
  "tall", "tame", "tangible", "tasteful", "tasty", "taut", "tenacious", "tender", "terrific", "thankful",
  "therapeutic", "thick", "thorough", "thoughtful", "thrilling", "thriving", "tidy", "tight", "timeless", "timely",
  "tireless", "titanic", "together", "tolerant", "top", "topnotch", "total", "tough", "traditional", "tranquil",
  "transcendent", "transparent", "tremendous", "trendy", "tribal", "trim", "triple", "triumphant", "tropical", "true",
  "trusting", "trustworthy", "trusty", "truthful", "twinkling", "typical", "ultimate", "ultra", "unassuming", "unbeatable",
  "unbiased", "unconditional", "undeniable", "understanding", "understood", "undisputed", "unfailing", "unforgettable", "unified", "unique",
  "united", "universal", "unlimited", "unmatched", "unparalleled", "unreal", "unrivaled", "unshakable", "unusual", "unwavering",
  "upbeat", "upcoming", "updated", "uplifting", "upper", "upright", "upscale", "upstanding", "upward", "urban",
  "urgent", "usable", "useful", "usual", "utmost", "utter", "valiant", "valid", "valuable", "valued",
  "vanilla", "varied", "vast", "vegan", "velvet", "venerable", "venturous", "verified", "versatile", "very",
  "veteran", "viable", "vibrant", "victorious", "vigilant", "vigorous", "vintage", "violet", "virtual", "virtuous",
  "visible", "visionary", "vital", "vivacious", "vivid", "vocal", "volcanic", "voluntary", "warm", "wealthy",
  "weekly", "welcome", "welcoming", "well", "western", "whimsical", "white", "whole", "wholesome", "wide",
  "wild", "willing", "winning", "wintry", "wired", "wise", "witty", "wizardly", "woke", "wonderful",
  "wondrous", "wooden", "worldly", "worldwide", "worshipful", "worth", "worthwhile", "worthy", "youthful", "zany",
  "zealous", "zen", "zesty", "zippy", "zodiac", "zonal",
  // Nature-inspired
  "alpine", "amber", "aqua", "arctic", "autumn", "azure", "bamboo", "birch", "bloom", "blossom",
  "breeze", "brook", "canyon", "cedar", "cherry", "cliff", "cloud", "clover", "cobalt", "copper",
  "coral", "cotton", "creek", "crimson", "crystal", "cypress", "daisy", "dawn", "delta", "desert",
  "dew", "dove", "dune", "dusk", "ebony", "elm", "ember", "fern", "field", "fjord",
  "flame", "flora", "flower", "foam", "fog", "forest", "frost", "garden", "garnet", "glade",
  "glen", "glow", "granite", "grass", "grove", "harbor", "harvest", "haven", "hazel", "heath",
  "heather", "hedge", "herb", "highland", "hill", "hollow", "honey", "horizon", "ice", "indigo",
  "iris", "island", "ivory", "ivy", "jade", "jasmine", "jet", "jungle", "lake", "laurel",
  "lava", "lavender", "lawn", "leaf", "lemon", "light", "lilac", "lily", "lime", "linen",
  "lotus", "lunar", "magnolia", "mango", "maple", "marble", "marine", "marsh", "meadow", "midnight",
  "mineral", "mint", "mist", "misty", "moon", "moss", "mountain", "mulberry", "nectar", "oak",
  "oasis", "ocean", "olive", "onyx", "opal", "orchid", "palm", "paper", "peach", "pearl",
  "pebble", "pepper", "pine", "pink", "plum", "polar", "pond", "poplar", "poppy", "prairie",
  "prism", "pumpkin", "quartz", "rain", "rainbow", "rainy", "ravine", "reef", "ridge", "river",
  "rock", "rose", "ruby", "russet", "saffron", "sage", "sand", "sandy", "sapphire", "savanna",
  "scarlet", "sea", "shadow", "shore", "silk", "silver", "sky", "slate", "smoke", "snow",
  "snowy", "solar", "spring", "spruce", "star", "stellar", "stone", "storm", "stream", "summer",
  "summit", "sun", "sunny", "sunrise", "sunset", "surf", "teal", "terra", "thunder", "tide",
  "timber", "topaz", "trail", "tree", "tulip", "turquoise", "twilight", "valley", "velvet", "verdant",
  "violet", "volcano", "walnut", "wave", "wheat", "willow", "wind", "windy", "winter", "wisteria",
  "wood", "woodland", "yarrow", "zephyr",
  // Tech-inspired
  "binary", "bit", "byte", "cache", "chip", "circuit", "cloud", "code", "cyber", "data",
  "digital", "disk", "echo", "fiber", "flash", "flux", "gamma", "gigabit", "grid", "hash",
  "helix", "hex", "hyper", "ion", "kernel", "laser", "link", "logic", "loop", "matrix",
  "mega", "mesh", "metro", "micro", "nano", "net", "neural", "nexus", "node", "nova",
  "omega", "orbit", "oxide", "parallel", "particle", "phase", "photon", "pixel", "plasma", "port",
  "prism", "probe", "proto", "pulse", "quantum", "quark", "radar", "radio", "ray", "reactor",
  "relay", "retro", "robo", "rocket", "satellite", "scalar", "scan", "sector", "serial", "server",
  "signal", "silicon", "smart", "solar", "sonic", "spark", "spectrum", "sphere", "static", "stealth",
  "sync", "techno", "tensor", "terminal", "tesla", "thermal", "titan", "token", "turbo", "ultra",
  "unified", "unit", "vector", "vertex", "virtual", "void", "volt", "vortex", "wave", "wifi",
  "wire", "zero", "zone"
];



