/**
 * Extensive list of common, safe-for-work nouns for burner email generation.
 * Combined with adjectives and numbers, this provides billions of unique combinations.
 */
export const nouns: string[] = [
  // Animals
  "albatross", "alpaca", "ant", "antelope", "ape", "armadillo", "badger", "bat", "bear", "beaver",
  "bee", "beetle", "bison", "bluebird", "boar", "bobcat", "buffalo", "butterfly", "camel", "canary",
  "capybara", "cardinal", "caribou", "cat", "catfish", "cheetah", "chipmunk", "clam", "cobra", "cockatoo",
  "cod", "condor", "coral", "cougar", "cow", "coyote", "crab", "crane", "cricket", "crocodile",
  "crow", "cuckoo", "deer", "dingo", "dog", "dolphin", "donkey", "dove", "dragon", "dragonfly",
  "duck", "eagle", "eel", "egret", "elephant", "elk", "emu", "falcon", "ferret", "finch",
  "firefly", "fish", "flamingo", "fly", "fox", "frog", "gazelle", "gecko", "gerbil", "giraffe",
  "goat", "goldfish", "goose", "gorilla", "grasshopper", "grizzly", "groundhog", "grouse", "gull", "hamster",
  "hare", "hawk", "hedgehog", "heron", "hippo", "hornet", "horse", "hound", "hummingbird", "hyena",
  "ibis", "iguana", "impala", "jackal", "jaguar", "jay", "jellyfish", "kangaroo", "kestrel", "kingfisher",
  "kite", "kiwi", "koala", "koi", "komodo", "ladybug", "lark", "lemur", "leopard", "lion",
  "lizard", "llama", "lobster", "locust", "loon", "lynx", "macaw", "magpie", "mallard", "mammoth",
  "manatee", "mandrill", "mantis", "marlin", "marmot", "marten", "meadowlark", "meerkat", "mockingbird", "mole",
  "mongoose", "monkey", "moose", "moth", "mouse", "mule", "mussel", "narwhal", "newt", "nightingale",
  "ocelot", "octopus", "okapi", "opossum", "orangutan", "orca", "oriole", "osprey", "ostrich", "otter",
  "owl", "ox", "oyster", "panda", "panther", "parakeet", "parrot", "partridge", "peacock", "pelican",
  "penguin", "perch", "pheasant", "pig", "pigeon", "pike", "piranha", "platypus", "polar", "pony",
  "porcupine", "porpoise", "possum", "prairie", "prawn", "puffin", "puma", "python", "quail", "rabbit",
  "raccoon", "ram", "raven", "ray", "reindeer", "rhino", "roadrunner", "robin", "rooster", "salamander",
  "salmon", "sardine", "scorpion", "seagull", "seahorse", "seal", "shark", "sheep", "shrimp", "skylark",
  "sloth", "snail", "snake", "sparrow", "spider", "squid", "squirrel", "stag", "starfish", "starling",
  "stingray", "stork", "sturgeon", "swan", "swift", "swordfish", "tapir", "tarpon", "termite", "tern",
  "thrush", "tiger", "toad", "toucan", "trout", "tuna", "turkey", "turtle", "unicorn", "viper",
  "vulture", "wallaby", "walrus", "warthog", "wasp", "weasel", "whale", "wildcat", "wolf", "wolverine",
  "wombat", "woodpecker", "wren", "yak", "zebra",
  // Nature
  "acorn", "aurora", "avalanche", "basin", "bay", "beach", "blizzard", "blossom", "boulder", "breeze",
  "brook", "canyon", "cascade", "cave", "cavern", "cedar", "cliff", "cloud", "coast", "cove",
  "crater", "creek", "crest", "delta", "desert", "dew", "dune", "dust", "earth", "ember",
  "estuary", "evergreen", "fern", "field", "fjord", "flame", "flare", "flower", "fog", "forest",
  "frost", "garden", "geyser", "glacier", "glade", "glen", "gorge", "granite", "grass", "grove",
  "harbor", "haven", "heath", "hill", "hollow", "horizon", "hurricane", "ice", "inlet", "island",
  "jungle", "lagoon", "lake", "lava", "leaf", "lightning", "lotus", "marsh", "meadow", "mesa",
  "meteor", "mist", "monsoon", "moon", "moss", "mountain", "nebula", "oasis", "ocean", "orchid",
  "peak", "pebble", "peninsula", "pine", "plain", "planet", "plateau", "pond", "prairie", "quake",
  "rain", "rainbow", "rapids", "ravine", "reef", "ridge", "river", "rock", "sand", "savanna",
  "sea", "shadow", "shore", "sky", "snow", "spring", "star", "stone", "storm", "stream",
  "summit", "sun", "sunrise", "sunset", "surf", "swamp", "tempest", "thunder", "tide", "timber",
  "tornado", "trail", "tree", "tsunami", "tundra", "valley", "volcano", "waterfall", "wave", "willow",
  "wind", "winter", "woods",
  // Objects
  "anchor", "anvil", "arrow", "atlas", "badge", "balloon", "banner", "barrel", "basket", "beacon",
  "bell", "blade", "blanket", "board", "boat", "book", "boot", "bottle", "bow", "box",
  "branch", "brick", "bridge", "brush", "bucket", "button", "cable", "cage", "camera", "candle",
  "cannon", "canvas", "cape", "card", "carpet", "cart", "castle", "chain", "chair", "chalk",
  "chest", "chimney", "chip", "clock", "cloth", "clover", "coat", "coin", "column", "compass",
  "cone", "cord", "cork", "corner", "couch", "cradle", "crown", "crystal", "cube", "cup",
  "curtain", "cushion", "dagger", "desk", "dial", "diamond", "dice", "disk", "dome", "door",
  "drum", "engine", "fan", "feather", "fence", "fiber", "flag", "flask", "flute", "fork",
  "frame", "funnel", "gadget", "gate", "gem", "glass", "globe", "glove", "gong", "grain",
  "guitar", "hammer", "handle", "harp", "harness", "hat", "hatch", "helm", "helmet", "hook",
  "horn", "hourglass", "jar", "jewel", "journal", "jug", "keel", "kettle", "key", "keystone",
  "kite", "knife", "knob", "knot", "ladder", "lamp", "lantern", "latch", "leaf", "lens",
  "lever", "lid", "line", "link", "lock", "locket", "loom", "loop", "magnet", "mail",
  "mantle", "map", "marble", "mask", "mast", "medal", "medallion", "mirror", "mold", "mortar",
  "mosaic", "motor", "mug", "nail", "needle", "nest", "net", "note", "oar", "orb",
  "organ", "paddle", "page", "pail", "pan", "panel", "paper", "parcel", "patch", "path",
  "pearl", "pedal", "pen", "pencil", "pendant", "perch", "piano", "pick", "pillar", "pillow",
  "pin", "pipe", "pivot", "plane", "plank", "plate", "plow", "plug", "pocket", "pod",
  "pole", "portal", "post", "pot", "pouch", "press", "prism", "propeller", "pulley", "pump",
  "quill", "rack", "rail", "ramp", "ring", "rivet", "rod", "roll", "roof", "rope",
  "rudder", "rug", "ruler", "saddle", "sail", "scale", "scanner", "scarf", "scope", "screen",
  "scroll", "seal", "seam", "seat", "shade", "shaft", "sheath", "sheet", "shelf", "shell",
  "shield", "ship", "shuttle", "signal", "silo", "sketch", "slab", "slate", "sled", "sleeve",
  "sling", "socket", "sofa", "spark", "spear", "sphere", "spike", "spindle", "spiral", "spoke",
  "spool", "spoon", "staff", "stage", "stair", "stake", "stamp", "stand", "staple", "strap",
  "string", "stripe", "switch", "sword", "symbol", "table", "tablet", "tack", "tag", "tank",
  "tape", "target", "tent", "thread", "throne", "tile", "timber", "tin", "token", "tool",
  "torch", "tower", "track", "trailer", "train", "trap", "tray", "treble", "triangle", "trophy",
  "trunk", "tube", "tunnel", "turret", "umbrella", "urn", "valve", "van", "vane", "vase",
  "vault", "veil", "vessel", "visor", "wagon", "wand", "watch", "wedge", "wheel", "whistle",
  "wick", "widget", "window", "wing", "wire", "wreath", "yacht", "zipper",
  // Abstract/Concepts
  "advent", "aether", "agenda", "alchemy", "alliance", "alpha", "ambition", "anthem", "apex", "arc",
  "archive", "aria", "aura", "aurora", "axiom", "balance", "ballad", "beacon", "beta", "bliss",
  "bloom", "bond", "boom", "boost", "bounty", "cache", "cadence", "calm", "canvas", "cascade",
  "catalyst", "chapter", "charm", "charter", "cipher", "circuit", "clarity", "climax", "code", "comet",
  "command", "concept", "contrast", "core", "cosmos", "courage", "covenant", "craft", "creed", "crest",
  "crusade", "cycle", "dawn", "delta", "destiny", "dimension", "doctrine", "domain", "drift", "drive",
  "dusk", "dynamo", "echo", "eclipse", "edge", "element", "emblem", "empire", "endeavor", "energy",
  "enigma", "epoch", "era", "essence", "ethos", "event", "exodus", "facet", "factor", "fame",
  "fate", "flair", "flash", "flight", "flow", "flux", "focus", "force", "forge", "form",
  "formula", "fortune", "fountain", "frame", "freedom", "frontier", "fusion", "future", "galaxy", "gamma",
  "gateway", "genesis", "genius", "glow", "grace", "gravity", "grid", "guild", "gusto", "harmony",
  "haven", "heart", "herald", "hero", "honor", "hope", "horizon", "hub", "hue", "icon",
  "idea", "ideal", "identity", "illusion", "image", "impact", "impulse", "index", "infinity", "insight",
  "instinct", "intellect", "intent", "ion", "journey", "joy", "junction", "karma", "kernel", "key",
  "kindle", "kingdom", "knight", "knot", "lancer", "landmark", "latitude", "lattice", "launch", "layer",
  "league", "legacy", "legend", "lens", "level", "liberty", "lift", "light", "limit", "link",
  "logic", "loop", "lore", "luck", "lumen", "luster", "mantra", "margin", "mark", "matrix",
  "maxim", "memory", "merit", "method", "metric", "might", "mind", "mirror", "mission", "mode",
  "model", "moment", "momentum", "motive", "motto", "muse", "mystery", "myth", "narrative", "nature",
  "nerve", "network", "nexus", "noble", "node", "norm", "north", "notion", "nova", "nucleus",
  "oath", "odyssey", "omega", "omen", "onset", "opal", "opera", "opus", "oracle", "orbit",
  "order", "origin", "outlook", "pace", "pact", "paradigm", "paradox", "parallel", "paragon", "passion",
  "path", "pattern", "pause", "peak", "phase", "phoenix", "pilot", "pinnacle", "pivot", "plan",
  "pledge", "plume", "point", "poise", "portal", "power", "praxis", "precision", "presence", "pride",
  "prime", "principle", "prism", "probe", "process", "profile", "progress", "promise", "proof", "protocol",
  "prowess", "pulse", "purpose", "pursuit", "quanta", "quantum", "quest", "quota", "radiance", "radius",
  "rally", "range", "rank", "rapture", "ratio", "ray", "reach", "realm", "reason", "reckoning",
  "record", "reflex", "reign", "relay", "reliance", "remedy", "renown", "resolve", "resonance", "respect",
  "response", "rhythm", "riddle", "rift", "rise", "rite", "ritual", "rival", "road", "rogue",
  "role", "root", "route", "routine", "royalty", "rule", "rune", "rush", "saga", "sage",
  "salute", "sanction", "sanctuary", "scale", "schema", "scheme", "scholar", "science", "scope", "scout",
  "script", "sector", "seed", "sense", "sentinel", "sequence", "serenity", "series", "service", "session",
  "shade", "shape", "shift", "shine", "signal", "signet", "silence", "silhouette", "silver", "simplicity",
  "skill", "slate", "slogan", "socket", "solace", "solstice", "solution", "sonata", "song", "soul",
  "source", "space", "span", "spark", "spectrum", "speed", "sphere", "spirit", "splendor", "sprint",
  "squad", "stage", "stance", "standard", "star", "status", "stealth", "steam", "steel", "step",
  "stimulus", "stitch", "storm", "story", "strategy", "streak", "stream", "strength", "stride", "strike",
  "stroke", "structure", "studio", "study", "style", "summit", "surge", "surplus", "survey", "symbol",
  "sync", "synergy", "syntax", "system", "tactic", "talent", "tango", "target", "task", "team",
  "tempo", "tenor", "tension", "term", "terrain", "testament", "texture", "theory", "thesis", "thirst",
  "thought", "thread", "threshold", "thrill", "throne", "thrust", "tide", "tier", "timber", "time",
  "titan", "title", "token", "tone", "torch", "torque", "touch", "tour", "trace", "track",
  "trade", "tradition", "trail", "trait", "trance", "transit", "treasure", "treaty", "trend", "trial",
  "tribute", "trigger", "trinity", "triumph", "trophy", "truce", "trust", "truth", "tune", "turbo",
  "twilight", "twist", "unity", "universe", "upgrade", "uprising", "urge", "utopia", "valor", "value",
  "vanguard", "variance", "vector", "velocity", "venture", "verdict", "verge", "version", "vertex", "vessel",
  "victory", "view", "vigor", "virtue", "vision", "vista", "vitality", "voice", "void", "volt",
  "volume", "vortex", "vow", "voyage", "wake", "ward", "warrant", "warp", "warrant", "watch",
  "wavelength", "wealth", "whirl", "will", "wind", "window", "wing", "wisdom", "wish", "wit",
  "wonder", "word", "work", "world", "worth", "wrath", "zenith", "zephyr", "zero", "zest",
  "zone", "zoom",
  // Tech/Modern
  "algorithm", "analog", "android", "antenna", "app", "array", "atom", "avatar", "axis", "bandwidth",
  "binary", "bit", "blockchain", "bot", "browser", "buffer", "byte", "cache", "channel", "chip",
  "circuit", "client", "cloud", "cluster", "codec", "compile", "config", "console", "cookie", "crypto",
  "cursor", "daemon", "dashboard", "data", "database", "debug", "decrypt", "depot", "device", "digital",
  "disk", "domain", "download", "driver", "drone", "echo", "electron", "email", "embed", "emoji",
  "encode", "encrypt", "engine", "ethernet", "export", "extension", "extract", "fiber", "file", "filter",
  "firewall", "firmware", "flash", "format", "framework", "frequency", "function", "gateway", "gigabyte", "glitch",
  "gradient", "graphics", "hack", "handle", "hardware", "hash", "header", "helix", "hex", "host",
  "hub", "hyperlink", "icon", "import", "index", "input", "instance", "interface", "internet", "kernel",
  "keyframe", "laser", "layer", "layout", "library", "link", "linux", "load", "localhost", "logic",
  "login", "loop", "macro", "mainframe", "malware", "matrix", "megabyte", "memory", "menu", "mesh",
  "metadata", "method", "microchip", "microwave", "middleware", "mobile", "modem", "module", "monitor", "motherboard",
  "network", "neuron", "node", "notification", "object", "offline", "online", "open", "operating", "operator",
  "optical", "output", "overflow", "packet", "parallel", "parser", "partition", "password", "patch", "payload",
  "peer", "peripheral", "permission", "photon", "ping", "pipeline", "pixel", "plasma", "platform", "plugin",
  "podcast", "pointer", "port", "portal", "prefix", "printer", "process", "processor", "program", "prompt",
  "protocol", "proxy", "pulse", "quantum", "query", "queue", "radar", "radio", "ram", "random",
  "reboot", "record", "refresh", "register", "relay", "render", "repo", "request", "reset", "resolution",
  "resource", "response", "restore", "robot", "root", "router", "runtime", "sandbox", "satellite", "scanner",
  "schema", "script", "scroll", "search", "sector", "security", "sensor", "sequence", "serial", "server",
  "session", "setup", "shader", "shell", "shortcut", "signal", "silicon", "simulator", "slider", "slot",
  "snapshot", "socket", "software", "solar", "solid", "sort", "source", "spam", "spectrum", "spider",
  "sprite", "stack", "startup", "static", "status", "storage", "stream", "string", "struct", "subnet",
  "suffix", "supercomputer", "surge", "switch", "sync", "syntax", "system", "tab", "table", "tag",
  "target", "task", "tech", "template", "tensor", "terminal", "terabyte", "test", "text", "theme",
  "thread", "thumbnail", "timestamp", "token", "toolbar", "tracker", "traffic", "transistor", "transport", "trigger",
  "tuple", "turbo", "type", "ultra", "unicast", "unit", "unix", "update", "upgrade", "upload",
  "uptime", "url", "user", "utility", "variable", "vector", "vendor", "version", "vertex", "video",
  "viewport", "virtual", "virus", "vision", "visual", "voltage", "volume", "vpn", "vram", "warp",
  "wavelength", "web", "webpage", "website", "widget", "wifi", "wiki", "window", "wireless", "wizard",
  "workflow", "workstation", "wrapper", "xml", "yield", "zero", "zigbee", "zip", "zone"
];



